apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: todo-service
spec:
  selector:
    app: training
  type: LoadBalancer
  ports:
    - name: todo-port
      port: 8080
      targetPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  selector:
    matchLabels:
      app: todo
      version: v0
  replicas: 3
  template:
    metadata:
      labels:
        app: todo
        version: v0
    spec:
      containers:
      - name: todo-container
        image: {{.Values.image}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /todo
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 1
